# Generated by Django 4.2.4 on 2023-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_image_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://i.stack.imgur.com/l60Hf.png'),
        ),
    ]
